name: Rebuild Images
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  build-docker-images:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          curl "https://raw.githubusercontent.com/pelias/ci-tools/master/build-docker-images.sh" | bash -
